env: CartPole-v1                                                  # environnement
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 10
nbTest: 1
freqVerbose: 10
freqOptim: 10                                                                          # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 30000
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 300
lr: 0.0004
explo: .1
prior: true
target: true
gamma: 0.95
decay: 0.99999
C: 1000
batch_size: 100
capacity: 10000
