batch_size: 1280
capacity: 100000
env: LunarLanderContinuous-v2
freqOptim: 1000
freqSave: 1000
freqTest: 10
freqVerbose: 10
fromFile: null
gamma: 0.99
lr_pi: 0.001
lr_q: 0.003
maxLengthTest: 1000
maxLengthTrain: 1000
nbEpisodes: 100000
nbTest: 1
optimStep: 5
ru: 0.99
seed: 5
