env: gridworld-v0                                                                     # environnement
map: gridworldPlans/plan2.txt                                                         # carte a charger
rewards:                                                                              # rewards de l'environnement
  0: -0.001
  3: 1
  4: 1
  5: -1
  6: -1
seed: 5                                                                               # graine aleatoire
featExtractor: !!python/name:__main__.MapFromDumpExtractor2 ''                        # Extracteur de features a partir de l'observation
freqSave: 1000
freqTest: 10
nbTest: 1
freqVerbose: 10
freqOptim: 4000                                                                          # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 1000000
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 500
lr_pi: 0.0001
lr_v: 0.0003
explo: 0.1
gamma: 0.99
Lambda: 0.99
optimStep: 10
capacity: 10000 
execute: |                                                                            # a executer apres le chargement de l'environnement
    env.setPlan(config["map"], config["rewards"])