env: CartPole-v1                                                  # environnement
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 10
nbTest: 1
freqVerbose: 10
freqOptim: 4000                                                                          # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 1000000
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 500
lr_pi: 0.0001
lr_v: 0.0003
explo: 0.1
gamma: 0.99
Lambda: 0.99
optimStep: 10
capacity: 10000 
