C: 1000
batch_size: 100
capacity: 10000
decay: 0.99999
env: CartPole-v1
explo: 0.1
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 10
freqSave: 1000
freqTest: 10
freqVerbose: 10
fromFile: null
gamma: 0.999
lr: 0.0003
maxLengthTest: 500
maxLengthTrain: 300
nbEpisodes: 1000000
nbTest: 1
optimStep: 10
seed: 5
