batch_size: 1000
capacity: 1000000
env: MountainCarContinuous-v0
freqOptim: 1000
freqSave: 1000
freqTest: 10
freqVerbose: 10
fromFile: null
gamma: 0.95
lr_pi: 0.001
lr_q: 0.003
maxLengthTest: 200
maxLengthTrain: 200
nbEpisodes: 1000000
nbTest: 1
optimStep: 10
ru: 0.9
seed: 5
