alpha: 0.2
batch_size: 100
capacity: 1000000
entropy_0: 0.2
env: Pendulum-v1
freqOptim: 1000
freqSave: 1000
freqTest: 10
freqVerbose: 10
fromFile: null
gamma: 0.99
lr_alpha: 0.001
lr_pi: 0.001
lr_q: 0.001
maxLengthTest: 1000
maxLengthTrain: 1000
nbEpisodes: 1000000
nbTest: 1
ru: 0.995
seed: 5
update_many: 50
